name: testing and coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt,clippy
    
      - name: run lint
        run: cargo fmt --check

      - name: run code check with clippy
        uses: giraffate/clippy-action@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          clippy_flags: -- -Dwarnings
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-review'

      - name: run code check with clippy
        if: ${{ github.event_name != 'pull_request' }}
        run: cargo clippy --tests -- -D warnings

      - name: install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: run tests
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: upload code coverage results
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: false
